language: ruby

rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-head

before_install:
  - gem update --system

env:
  global:
    - JRUBY_OPTS=--dev

script:
  - bundle exec rake ${TEST_SUITE:-test}

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: TEST_SUITE=templates:test
  include:
    - env: TEST_SUITE=templates:test
      rvm: 2.5.1
