language: ruby

rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.1
  - ruby-head

script:
  - bundle exec rake ${TEST_SUITE:-test}

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - env: TEST_SUITE=templates:test
  include:
    - env: TEST_SUITE=templates:test
      rvm: 2.4.1
