language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2
  - jruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby
before_script:
  - RAILS_ENV=test bundle exec rake --rakefile=test/dummy/Rakefile db:setup
