language: ruby

rvm:
  - 2.3.1
  - 2.2.5
  - ruby-head
  - rbx-2
  - jruby

env:
  global:
    - JRUBY_OPTS=--dev

script:
  - bundle exec rake ${TEST_SUITE:-test}

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby
    - env: TEST_SUITE=test:templates
  include:
    - env: TEST_SUITE=test:templates
      rvm: 2.2
